### ISSUE TITLE
OfflineModeBadge not found

### ISSUE THREAD

**Issue by GetterDragon** [ringcentral/ringcentral-js-widgets#1599]
Trying to run through your steps and when I get to yarn start, it fails with:

ERROR in ./src/containers/AppView/index.js
Module not found: Error: Can't resolve 'ringcentral-widgets/components/OfflineModeBadge' in 'C:\Users\xxxxxxxx\RC_Node_Apps\Queue_and_Presence\src\containers\AppView'
 @ ./src/containers/AppView/index.js 19:24-82
 @ ./src/containers/App/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.js
webpack: Failed to compile.

When I look at the index.js file for the Import it's trying to do:

import OfflineModeBadge from 'ringcentral-widgets/components/OfflineModeBadge';

There is no OfflineModeBadge in that directory nor do I see one online here.

This is on a Windows 10 (64bit) machine, with Node.js 10.16.3 LTS and Yarn 1.19.0

**Comment by embbnux** [comment]
Hi @GetterDragon Sorry for this. The tutorial is outdated. Will update it soon. Now we replace OfflineModeBadge with ConnectivityBadgeContainer.
You can follow her:
https://github.com/ringcentral/ringcentral-embeddable/blob/master/src/containers/App/index.js#L106
https://github.com/ringcentral/ringcentral-embeddable/blob/master/src/containers/AppView/index.js
https://github.com/ringcentral/ringcentral-embeddable/blob/master/src/modules/Phone/index.js#L116

**Comment by embbnux** [comment]
Hi @GetterDragon, we have updated CLI tool and tutorials. It requires CLI(0.1.0) and widgets library(0.10.13). 
Feel free to raise issues in here.
Thanks so much for your feedback.

**Comment by embbnux** [comment]
Closed by inactive. Feel free to reopen.
