### ISSUE TITLE
On Groups related modules and Groups API deprecation

### ISSUE THREAD

**Issue by LautaroJayat** [ringcentral/ringcentral-js-widgets#1674]
Sorry if this is not the place, but I was wondering how safe is to use Group related modules and widgets.
This doubt comes from the fact that RingCentral has marked this API as deprecated. I could not found any information on until when it will be available, nor if it was insecure or something.
So, is secure to still be using modules that uses these endpoints?

Thanks for your time.

PD: This are the deprecated endpoints:
* https://developers.ringcentral.com/api-reference/Chats/listGlipGroups
* https://developers.ringcentral.com/api-reference/Chats/createGlipGroup
* https://developers.ringcentral.com/api-reference/Chats/readGlipGroup
* https://developers.ringcentral.com/api-reference/Chats/assignGlipGroupMembers

**Comment by embbnux** [comment]
Hi @LautaroJayat For compatibility, those APIs are still supported. But I am not sure when they will be removed. You can send help case to RingCentral Developer support directly https://developers.ringcentral.com/support/create-case
