### ISSUE TITLE
CLI tool is outdated

### ISSUE THREAD

**Issue by frankpaul142** [ringcentral/ringcentral-js-widgets#1679]
Hello, all the dependecies are broken and the ring-central CLI is trying to install an old version of ringcentral-integration (0.11)

**Comment by embbnux** [comment]
Hi @frankpaul142 Yeah, the cli tool is outdated with latest widgets lib. Will fix it soon.
For now, you can use the https://github.com/ringcentral-tutorials/ringcentral-widgets-demo to have the app work with `yarn`.

And you can also try your online widget project "RingCentral Embeddable" https://github.com/ringcentral/ringcentral-embeddable. You don't need to build the widget by yourself. Just use API to interact with it.

**Comment by frankpaul142** [comment]
Hi, thanks for the reply, I checked the https://github.com/ringcentral-tutorials/ringcentral-widgets-demo, but it has the same issue when you answer, I'm getting this error, maybe we need to do something different ? thanks !
<img width="1125" alt="Captura de Pantalla 2021-08-14 a la(s) 09 22 03" src="https://user-images.githubusercontent.com/9060783/129449419-0cebb75e-4ffa-4b59-ae40-3dc042b5c079.png">

**Comment by embbnux** [comment]
Do you use yarn to install dependencies? The project has yarn.lock to make sure you install right widgets version

**Comment by embbnux** [comment]
Hi @frankpaul142 I updated widgets demo to support latest widgets lib https://github.com/ringcentral-tutorials/ringcentral-widgets-demo
And will update CLI tool and tutorials in this week

**Comment by embbnux** [comment]
CLI tool and tutorials is updated https://ringcentral-tutorials.github.io/ringcentral-widgets-demo/
For CLI tool, please update it into 0.3.0

**Comment by embbnux** [comment]
Closed by inactive. Feel free to reopen it if you still have issue.
