### ISSUE TITLE
Component broken when you answer 

### ISSUE THREAD

**Issue by frankpaul142** [ringcentral/ringcentral-js-widgets#1680]
Hello, when you try to answer a call on the demo created with the CLI, we are getting this error and a WhiteScreen
<img width="1574" alt="Captura de Pantalla 2021-08-13 a la(s) 11 39 45" src="https://user-images.githubusercontent.com/9060783/129391836-aa3efd2a-1bcf-43e1-b88b-cedc9289baa8.png">

**Comment by embbnux** [comment]
Same as #1679 . The CI and docs are outdate. https://github.com/ringcentral/ringcentral-js-widgets/issues/1679#issuecomment-898865693
