### ISSUE TITLE
Undefined variable $header-height

### ISSUE THREAD

**Issue by calebbergman** [ringcentral/ringcentral-js-widgets#1689]
## Environment
*Node*: 16.13.0
*ringcentral-widgets*: 0.12.6
*sass-loader*: 7.3.1

## Issue
```
ERROR in ./node_modules/ringcentral-widgets/components/SettingsPanel/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/postcss-loader/src??ref--8-2!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./node_modules/ringcentral-widgets/components/SettingsPanel/styles.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

  height: calc(100% - $header-height);
                     ^
      Undefined variable.
   ╷
23 │   height: calc(100% - $header-height);
   │                       ^^^^^^^^^^^^^^
   ╵
  stdin 23:23  root stylesheet
      in C:\Path\To\App\node_modules\ringcentral-widgets\components\SettingsPanel\styles.scss (line 23, column 23)
 @ ./node_modules/ringcentral-widgets/components/SettingsPanel/styles.scss 2:14-172 21:1-42:3 22:19-177
 @ ./node_modules/ringcentral-widgets/components/SettingsPanel/SettingItems/SwitchLineItem.js
 @ ./node_modules/ringcentral-widgets/components/SettingsPanel/SettingsPanel.js
 @ ./node_modules/ringcentral-widgets/components/SettingsPanel/index.js
 @ ./src/containers/SettingsPage/index.js
 @ ./src/containers/App/index.js
 @ ./src/app.js
 @ multi @babel/polyfill ./src/app.js
```

Adding an import to [commonStyles/layout.scss](https://github.com/ringcentral/ringcentral-js-widgets/blob/master/packages/ringcentral-widgets/lib/commonStyles/layout.scss) - which defines such a variable - at the top of the [SettingsPanel style's](https://github.com/ringcentral/ringcentral-js-widgets/blob/master/packages/ringcentral-widgets/components/SettingsPanel/styles.scss) resolves the issue and the application can then build. Unsure if this is the solution or simply a workaround.

**Comment by embbnux** [comment]
Hi @calebbergman It should be a bug at 0.12.6 that $header-height is not import at SettingsPanel.
You can add it in `theme.scss` file.  
```scss
$header-height: 40px;
```
`theme.scss` folder should be included in sass-loader webpack settings https://github.com/ringcentral/ringcentral-js-widgets/blob/0.12.6/packages/ringcentral-widgets-demo/dev-server/webpack.config.js#L75

**Comment by embbnux** [comment]
closed by inactive
