### ISSUE TITLE
https://api.ringcentral.com/rcvideo/v1/bridges 404 (Not Found)

### ISSUE THREAD

**Issue by calebbergman** [ringcentral/ringcentral-js-widgets#1705]
**Module version**: 0.12.3

As of at least today, the `phone.rcVideo.startMeeting()` call is returning a 404 for url https://api.ringcentral.com/rcvideo/v1/bridges. There were some RingCentral outages over the last couple of days. I am unsure if maybe there was an API change and this route just doesn't exist anymore?

**Comment by embbnux** [comment]
Hi @calebbergman the rcvideo api (beta) v1 is deprecated and removed. We need to switch into v2.
Let me show the example code later.

**Comment by embbnux** [comment]
@calebbergman The API should not be removed. I have created internal ticket for this. 
For now, you can use this path to fix it https://github.com/ringcentral/ringcentral-embeddable/pull/611

**Comment by embbnux** [comment]
@calebbergman It is fixed at server side. You don't need to use the patch.

**Comment by embbnux** [comment]
Thanks so much for confirming it. I will close this.
