### ISSUE TITLE
Cannot run test on CI when developer open a PR

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-js-widgets#344]
Testing only can be run in master branch. In PR, CI failed caused by wrong env variables.

**Comment by tylerlong** [comment]
Known issue.  https://docs.travis-ci.com/user/environment-variables/

> Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.

**Comment by tylerlong** [comment]
I am trying to encrypt env vars and add them to `.travis.yml`. Stay tuned.

**Comment by embbnux** [comment]
Tests is disabled now. We need to fix it

**Comment by embbnux** [comment]
Fixed
