### ISSUE TITLE
no i18n string in welcome page

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-js-widgets#385]
Sometimes, app will show `loginButton` not `Sign In` in welcome page.

**Comment by u9520107** [comment]
@embbnux this happens mainly in Chrome extension? I suspect it has something to do with the proxied locale module.

**Comment by embbnux** [comment]
Yes, It happens mainly in Chrome extension.

**Comment by embbnux** [comment]
fixed now
