### ISSUE TITLE
Improve Widget Demo Code

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-js-widgets#392]
- [x] Provide both the iframe and JS ways to setup widgets

- [x] Allow user to replace app parameters(key/secret/redirectUri) when deploying 

- [x] Host the widget code in CDN 

- [x] List permissions required for the app in README

**Comment by embbnux** [comment]
All supported in [RingCentral Embeddable](https://github.com/ringcentral/ringcentral-embeddable)
