### ISSUE TITLE
Rename project to ringcentral-js-widgets

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-js-widgets#420]

**Comment by u9520107** [comment]
List of actions to take:
- [ ] Rename repository to "ringcentral-js-widgets"
- [ ] Publish to npm as "ringcentral-js-widgets"
- [ ] Deprecate ringcentral-widget package on npm

**Comment by embbnux** [comment]
Published to npm as "ringcentral-widgets"
