### ISSUE TITLE
Allow embed widgets in third party website by using simple template tags

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-js-widgets#58]
Similar to https://publish.twitter.com

We need to provide a mechanism that other developers can embed the widget into their website by using things like 
`<a class="twitter-timeline" href="https://twitter.com/TwitterDev/lists/national-parks">A Twitter List by TwitterDev</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>`

For first version, we don't need to provide customization parameters. Just include all features provided by widgets.

**Comment by embbnux** [comment]
Provided [RingCentral Embeddable](https://github.com/ringcentral/ringcentral-embeddable) to support this. Move related issue to [RingCentral Embeddable](https://github.com/ringcentral/ringcentral-embeddable/issues)
