### ISSUE TITLE
* button is not aligned center

### ISSUE THREAD

**Issue by huanhulan** [ringcentral/ringcentral-js-widgets#585]
the [*] button is not aligned center. the UI issue is caused by missing `text-anchor` attribute and wrong placement attributes value, the correct one should be:
```html
<text class="node_modules-ringcentral-widgets-components-DialButton-_styles_btnValue_3Jk0B node_modules-ringcentral-widgets-components-DialButton-_styles_special_FZBPm" x="250" dx="0" y="250" dy="100" text-anchor="middle"></text>
```
PS: the `dy` attribute's value above maybe incorrect because it is estimated by human eye. : )

**Comment by embbnux** [comment]
fixed
