### ISSUE TITLE
Text input does not work well when using IME

### ISSUE THREAD

**Issue by ele828** [ringcentral/ringcentral-js-widgets#797]
When updating Controlled Input Component using IME asynchronously (via proxy), the value of input will be in a mess.

There are two possible solutions:
1. Use Composition Event to handle IME input event (the drawback is that Composition Event behaves differently across different browsers)
2. Turn Controlled Input into Self-Controlled Input and combining the onFocus and onBlur event to control the props receiving process. (easier to implement)

**Comment by embbnux** [comment]
Related with #840
